export * from './account.service';
import { AccountService } from './account.service';
export * from './goal.service';
import { GoalService } from './goal.service';
export * from './identity.service';
import { IdentityService } from './identity.service';
export * from './report.service';
import { ReportService } from './report.service';
export * from './transaction.service';
import { TransactionService } from './transaction.service';
export * from './user.service';
import { UserService } from './user.service';
export * from './weatherForecast.service';
import { WeatherForecastService } from './weatherForecast.service';
export const APIS = [AccountService, GoalService, IdentityService, ReportService, TransactionService, UserService, WeatherForecastService];
